language: python

python:
  - "2.7"
  - "3.3"

env:
  - NEO4J_VERSION="1.9.4"
  - NEO4J_VERSION="2.0.2"

before_install:
  - . ./test/getneo.sh
  - ./lib/neo4j/bin/neo4j start || ( cat ./lib/neo4j/data/log/*.log && exit 1 )

install:
  - pip install pytest logutils

script:
  - py.test ./test
